---
bibliography: references.bib
#csl: csl/nlm-citation-sequence-brackets.csl
---

# Methods

## Study design and population

This study analysed data collected for the prospective CoLaus \textbar{} PsyCoLaus study as well as its substudy OsteoLaus. CoLaus includes citizens of Lausanne, Switzerland, aged 35 to 75 years, for a single-centre study between June 2003 and May 2006. Since then, four follow-up visits were conducted at the following timelines: first (2009–2013), second (2014–2018), third (2018–2021), forth (2022–2026). The focus of this analysis was on the OsteoLaus cohort, which included 1475 women aged 50 to 80 years at baseline [@shevroja2019]. All women participating in the Baseline visit for CoLaus were enrolled for OsteoLaus to study fracture risk and assess the relationship between osteoporosis and cardiovascular diseases. Women with the following inclusion criteria were selected: Written informed consent, BMI between 15 kg/m^2^ and 40 kg/m^2^, at least two vertebrae and the femur accessible for measurement, available information on previous osteoporotic fractures, quantitative ultrasound of the heel is accessible for measurement, no known disease affecting bone metabolism, and no known disorders affecting skeletal sites. On average, measurements were taken every 2.5 years with these timelines: first visit (baseline, 2010–2012, n = 1475), second (2012–2015, n = 1349), third (2015–2018, n = 1242), fourth (2017–2020, n = 1104), and fifth (2020–2022, n = 944) visits. The number of participants decreased over time due to loss of follow‐up, death, institutionalisation, refusal, body mass index (BMI) over 40 kg/m^2^ or severe psychiatric disease [@vendrami2025a]. Further details of the recruitment process and methodology for CoLaus and OsteoLaus are described in Firmann et al. [@firmann2008] and Shevroja et al. [@shevroja2019], respectively. Additional information can also be found at [www.colaus-psycolaus.ch](www.colaus-psycolaus.ch). Figure 1 illustrates the study population and visit timeline. <!--# check if this is the case -->

<!--# TBC -->

Link of CoLaus to the closest OsteoLaus visit...

## Exposure

Dietary intake, including dairy consumption, was assessed during the CoLaus visits from the first follow up visit onwards using a self-administered semi-quantitative food frequency questionnaire (FFQ). The FFQ was developed and validated in Geneva [@bernstein1995; @marques-vidal2018] and reflects the intake of 97 food items over the past 4 weeks. The questionnaire also included consumption frequencies ranging from “less than once during the last 4 weeks” to “2 or more times per day” and three different serving sizes (smaller, equal, or larger) for each item compared to a reference size [@marques-vidal2018]. The amount (either in g/day or mL/day) per item was calculated by multiplying frequency and portion size. Portion sizes were defined as seen in @tbl-PortionSize for dairy products. The FFQ responses were also converted into nutrients and energy based on the French CIQUAL food composition table [@ciqual].

| **FFQ** | **Description** | **Unit** | **Men (S / E / L)** | **Women (S / E / L)** |
|---------------|---------------|---------------|---------------|------------------|
| **1** | Plain yogurt | g | 90 / 180 / 270 | 90 / 180 / 270 |
| **2** | Low-fat yogurt | g | 90 / 180 / 270 | 90 / 180 / 270 |
| **3** | Fruit/aroma yogurt | g | 90 / 180 / 270 | 90 / 180 / 270 |
| **4** <!--# more for women? this is atypical check --> | Cottage cheese (0% fat) | g | 50 / 100 / 150 | 60 / 125 / 200 |
| **5** | Cottage cheese, ricotta | g | 50 / 100 / 150 | 50 / 100 / 150 |
| **6** | Feta, mozzarella | g | 30 / 60 / 90 | 20 / 40 / 60 |
| **7** | Gruyère, tomme, camembert | g | 40 / 80 / 120 | 30 / 60 / 90 |
| **8** | Cheese fondue | g | 175 / 350 / 525 | 175 / 350 / 525 |
| **52** | Butter | g | 5 / 10 / 15 | 4 / 7 / 10 |
| **53** | Cream (35% fat) | g | 10 / 20 / 30 | 8 / 15 / 23 |
| **63** | Cream tart, cream cake | g | 50 / 100 / 150 | 50 / 100 / 150 |
| **68** | Ice cream, sorbet | g | 60 / 120 / 180 | 50 / 100 / 150 |
| **71** | Butter (for cooking) | g | 5 / 10 / 15 | 4 / 7 / 10 |
| **82** | Milk in coffee (0% fat) | mL | 15 / 30 / 45 | 15 / 30 / 45 |
| **83** | Milk in coffee (non 0% fat) | mL | 15 / 30 / 45 | 15 / 30 / 45 |
| **84** | Coffee creamer | mL | 6 / 12 / 18 | 6 / 12 / 18 |
| **85** | Milk as drink (0% fat) | mL | 75 / 150 / 225 | 75 / 150 / 225 |
| **86** | Milk as drink (non 0% fat) | mL | 75 / 150 / 225 | 75 / 150 / 225 |

: : Overview of portion sizes for dairy products

|  |
|------------------------------------------------------------------------|
| \[\^1\]: Portion sizes are S: small, E: equal, and L: large compare the reference size. |

I calculated total dairy intake in grams as the combined amount of milk, cheese, yoghurt, cream, butter, and dairy-based desserts consumed (FFQ1 to FFQ8, FFQ52, FFQ53, FFQ63, FFQ68, FFQ71, FFQ82 to FFQ86). Two assumptions were made. Firstly, the density of dairy product is approximately 1 g/cm^3^ to be able to sum products with different units millilitre of gram. Secondly, the assessment of ice cream consumption was combined with sorbet (not dairy based) within one variable (FFQ68). For the amount of ice cream, the entire amount of FFQ68 was considered a dairy product.

For each dairy subtype, the total grams consumed were calculated by summing the amounts within each category. Yoghurt and cheese (FFQ1 to FFQ8) belonged to fermented dairy. Non-fermented dairy included milk, cream, and ice-cream (FFQ52, FFQ53, FFQ63, FFQ68, FFQ71, FFQ82 to FFQ86). Full-fat dairy contained the full-fat variants of milk, yoghurt, cheese, cream, butter and ice-cream (FFQ1, 3, 5, 6, 7, 8, 52, 53, 63, 68, 71, 83, 84, 86). Skimmed milk, yoghurt, and 1–2% fat cheese were categorised as low-fat dairy (FFQ2, 4, 82, 85).

In addition to total dairy intake, participants were classified as either meeting or not meeting the Swiss Society for Nutrition recommendations for daily dairy intake [@dairyguid]. This classification was determined by weighing each frequency score by the participant's self-reported portion size using following weights: Less"= 0.5, Equal = 1.0, Bigger = 1.5. Following dairy items counted towards the total intake: FFQ1 to FFQ8, FFQ85 and FFQ86. The other products were not included due to being consumed in small volumes and usually do not substantially add to the daily dairy intake.

Participants were grouped into quartiles based on their total dairy intake using cut-offs derived from the distribution at the first study visit. These same cut-offs were then applied to all subsequent visits.

Cumulative average dairy intake was calculated as the running mean of all non-missing dairy intakes from first measurment visit up to and including the current visit for each visit. Similarly, the cumulative average dairy intake lagging one visit was used for the sensitivity analysis.

<!--# need to decide if I do this with cumulative average -->

## Covariates

The covariates included in the analysis were selected based on prior evidence suggesting direct or indirect associations with muscle mass and physical function. Figure 2 presents a directed acyclic graph illustrating the assumed relationships between these variables.

### Sociodemographic

ßEducational level was self-reported and defined as the highest level of education completed. This value was only assessed at CoLaus baseline. It was grouped into three categories based on the International Standard Classification of Education (ISCED): low (ISCED 0-2), medium (ISCED 3), and high (ISCED 4-8) [@ISCED].

<!--# Why is educational level a covariant -->

"mrtsts2",

The age was derived by the birth date and examination date.

### **Anthropometric**

All participants had their height measured using the same portable stadiometer (Seca version 216, Seca, Chino, CA, USA) with precision 0.1 cm, and body weight with the same electronic scale (Seca Clara 803, Seca, Chino, CA, USA) with precision 0.1 kg. Both measurements were performed with the participant barefoot and in minimum clothing. Body mass index (BMI) was calculated as weight/height^2^. BMI was categorized into underweight (\< 18.5 kg/m^2^), normal (18.5-24.9 kg/m^2^), overweight (25.0–29.9 kg/m^2^), and obese (≥ 30.0 kg/m^2^) according to WHO guidelines <!--# [SOURCE] -->.

### Lifestyle

Smoking may indirectly affect muscle mass through lower levels of physical activity [@degens2015]. It may also directly contribute to muscle loss by reducing protein synthesis and increasing muscle breakdown through metabolic pathway changes. Thus, the smoking status of the participant was included as covariate. Smoking history of participants was collected through self-report. Participants were grouped into three categories:

- Current smokers: those who were actively smoking at the time of the study, regardless of how much they smoked
- Former smokers: those who had smoked in the past but had quit before the study, regardless of how long ago they quit
- Never smokers: those who had never smoked

Smoking status was recorded at each CoLaus study visit. Some reported changes were not realistic, for example, switching from never smoker to former or current smoker, or from former or current smoker to never smoker. In these cases, the “never smoker” status was changed to “former smoker”, assuming participants may have answered based on their current situation rather than their lifetime history.

Alcohol consumption is not consistently linked to lower grip strength or appendicular lean mass. However, some evidence suggests that higher intake may be associated with lower muscle mass in a dose-dependent manner. It was therefore included as a covariate <!--# source -->.

Alcohol consumption was assessed using two self-reported questionnaires. The first method asked participants how many alcoholic drinks they had consumed in the previous 7 days measured in units/week and was used for the main analysis. The second method asked about the number of glasses of wine, bottles of beer, or shots of spirits consumed in the past month measured in gram ethanol/day and was used for sensitivity analyses.

Based on these responses, the amount of units consumed per week was calculated. According to Swiss national guidelines, one standard drink was defined as one glass of wine, one bottle of beer, or one shot of spirits, each containing about 10 g to 12 g of pure ethanol [@standardglas]. The alcohol intake in grams per day was converted into units per week using 10 g of ethanol per unit. Participants were then grouped into four categories based on their total weekly alcohol intake:

- Non-drinkers: 0 units/week (0 g/day), which includes both lifetime and current abstainers.
- Light drinkers: ≥1 to 3 units/week (\>0–6 g/day), representing occasional consumption.
- Moderate drinkers: ≥4 to 7 units/week (\>6–12 g/day), representing frequent consumption within the Swiss low-risk limit for women.
- Heavy drinkers: \>7 units/week (\>12 g/day), categorized as hazardous consumption exceeding the Swiss national guidelines for women.

While this categorization provides a structured metric for analysis, it is noted that self-reported dietary and alcohol questionnaires often slightly underestimate absolute intake levels [@kerr2012; @morabia1994]. Validation studies in the Swiss population (Geneva) have specifically demonstrated that semi-quantitative FFQs tend to underestimate absolute alcohol consumption when compared to more intensive 24-hour recall methods [@morabia1994].

<!--# Why is physical activity used as covariant? -->

Physical activity (PA) is a key factor influencing muscle related outcomes <!--# source -->.

PA was measured using a Physical Activity Frequency Questionnaire (PAFQ) developed in 1998 for the Geneva population and containing 70 types of physical activity [@bernstein1998]. The questionnaire recorded how many days during the past week (0-7 days) each activity was performed and the duration per day (0-10 hours in 15-minute increments) \[@verhoog2019\]. Each activity was classified according to its metabolic equivalent of task (MET) value as sedentary behaviour (\< 2 METs), light physical activity (2 to \< 3 METs), moderate physical activity (3-6 METs), or vigorous physical activity (\> 6 METs).

This assessment was only available at the first and second follow-up visits of the CoLaus study. A previous study in a subpopulation of CoLaus showed a moderate correlation between self-reported activity levels measured with the PAFQ and accelerometer-based measurements of physical activity [@verhoog2019]. Since self-reported questionnaires tend to overestimate physical activity and underestimate sedentary behaviour, participants were categorised into tertiles representing low, moderate, and high physical activity levels.

The tertiles were defined using the combined amount of moderate and vigorous physical activity reported at the first follow-up visit and were then applied to all time points. Only moderate and vigorous physical activity were used because these measures showed the smallest difference compared with accelerometer-based assessments [@verhoog2019]. Tertiles were used because no established reference values were available.

### Dietary assessment

Total energy intake was calculated as the sum of all FFQ items, using energy values from the French CIQUAL food composition table [@ciqual].

### Clinical

The relationship between type 2 diabetes and sarcopenia is bidirectional and multifactorial [@chen2023]. While diabetes can promote muscle deterioration through insulin resistance, chronic inflammation, oxidative stress, and hyperglycemia-induced protein breakdown pathways *Y. Hirata et al., 2019*, reduced muscle mass conversely increases diabetes risk and worsens glucose metabolism *D. Sizoo et al., 2022.* Clinical evidence demonstrates that muscle deterioration in type 2 diabetes patients occurs independently of disease duration, metabolic control, and microvascular complications, suggesting intrinsic pathophysiological mechanisms beyond traditional diabetic complications *N. Guerrero et al., 2016.* Importantly, therapeutic interventions including glycemic control optimization and insulin therapy can improve muscle mass outcomes, indicating the potential reversibility of diabetes-associated muscle changes *K. Sugimoto et al., 2020.*

Diabetes status was assessed using three sources: self-report, fasting plasma glucose (FPG), and glycated hemoglobin (HbA1c). Self-report was based on the question “Have you ever been told that you had diabetes?”. Among the objective measures, HbA1c was considered the primary indicator due to its higher reliability and was used whenever available. If HbA1c was missing, FPG was used. If neither biomarkers were available, diabetes status was based on self-report.

Blood samples were collected in the morning after an overnight fast. Analyses were performed at the CHUV Clinical Laboratory on fresh samples within 2 hours of collection. Plasma glucose was measured using the glucose hexokinase method, with maximum inter- and intra-assay coefficients of variation of 1.6% and 0.8%, respectively. HbA1c was measured using high-performance liquid chromatography. Diabetes was defined as a fasting plasma glucose level ≥ 7.0 mmol/L or an HbA1c level ≥ 48 mmol/mol.

<!--# tbc -->

HRT

<!--# tbc -->

hypertension

### Medication and supplement use

The use of prescribed medication and supplements was assessed by self-report. Each drug type is descried with the Anatomical Therapeutic Chemical (ATC) Classification.

Lipid-lowering medications have been linked to muscle-related adverse effects in clinical reports [@shin2026]. However, evidence for an association with reduced muscle mass or impaired muscle function remains inconsistent, with some studies reporting negative associations [@shin2026] and others finding no effect [@fazel2026]. Lipid-lowering drugs were defined as all medications classified under ATC code C10.

systemic corticosteroid use is associated with reduced lean mass and grip strength <!--# source -->

benzodiazepine use

bisphosphonate use\

Vitamin D supplementation

calcium supplementation

## Outcome Variables

Handgrip strength (kg), measured using a JAMAR dynamometer

Appendicular lean mass (ALM) and derived indices (ALMI and ALM/BMI for sensitivity analysis), measured by DXA (GE Lunar iDXA™)

-\> different DXA methods use Lunar as main and check in sensitivity since not as simple to convert -\> reference paper

Gait speed (m/s), assessed using a 6-meter walk test

Sarcopenia

## Statistical Methods

Participants were classified into quartiles according to their baseline daily intake of dairy products (grams per day) for descriptive analysis.

### Missing values

The analysis was performed once with complete cases and once applying multiple imputation.

### Imputation

MICE

### Selection of Covariant

selection of covariates accoriding to what?

### Models

## Ethics

<!--# The Institutional Ethics Committee of the University of Lausanne approved the CoLaus/PsyCoLaus and, subsequently, the OsteoLaus studies. All participants signed a written informed consent form after having received a detailed description of the goal and funding of the studies. This article follows the STROBE guidelines [SOURCE].-->
