# Methods

## Study Population

The OsteoLaus study included a subgroup of the CoLaus \textbar{} PsyCoLaus study, including postmenopausal women aged 50 to 80 years at recruitment @shevroja2019. The recruitment process for CoLaus is specified elsewhere @firmann2008. OsteoLaus was initiated to focus on bone health and is a population-based prospective cohort from Lausanne, Switzerland. Participants were recruited between September 2009 and September 2012 if they participated in the baseline measurement of the CoLaus study. Women with the following inclusion criteria were selected: written informed consent, BMI between 15~$kg/m^2$ and 40~$kg/m^2$, at least two vertebrae and the femur accessible for measurement, available information on previous osteoporotic fractures, QUS of the heel accessible for measurement, no known disease affecting bone metabolism, and no known disorders affecting skeletal sites. On average, measurements were taken every 2.5 years, including the baseline and follow-ups. The timeline was as follows: F1: Follow-up 2009–2013, F2: Follow-up 2014–2018, F3: Follow-up 2018–2021, F4: Follow-up 2022–2026.

Figure 1 illustrates the study population.

## Exposure

FFQ self-reported food questionnaire

## Covariates

### Sociodemographic

xxxx

### Lifestyle

Smoking status (never, former, current; time-updated), alcohol intake, physical activity

### Dietary

xxx

### Clinical

xxxx
