# =============================================================================
# R/08_exclusion_graph.R
# =============================================================================
# Produces CONSORT-style participant flow diagrams from the flow logs
# generated by freeze_dataset().
#
# Functions:
#   make_hard_exclusion_graph()     Single vertical CONSORT diagram (hard excl.)
#   make_outcome_exclusion_graph()  One vertical diagram per outcome, stacked
#   make_combined_flow_graph()      Convenience wrapper returning both
#   export_exclusion_graph()        Write grViz to PNG or SVG
#

# =============================================================================

# TODO not correct yet
# =============================================================================
# Hard exclusion diagram
# =============================================================================

#' CONSORT-style flow diagram for hard (cross-outcome) exclusions.
#'
#' Single vertical centre column. Each exclusion criterion with n_excluded > 0
#' is shown as a horizontal box to the right with an arrow from the cohort
#' node immediately above it. Criteria with n_excluded = 0 are skipped to
#' keep the diagram uncluttered. Black and white.
#'
#' @param flow_log_hard Output of freeze_dataset()$flow_log_hard.
#' @param title         Title string displayed above the diagram.
#' @return DiagrammeR grViz object.
make_hard_exclusion_graph <- function(
        flow_log_hard,
        title = "Participant Flow \u2014 Hard Exclusions") {
    
    .check_diagrammer()
    
    # Step 0 = enrolment row; steps 1+ = exclusion criteria
    enrol_row  <- flow_log_hard[flow_log_hard$step == 0L, ]
    
    # Only show steps that actually excluded someone
    excl_rows  <- flow_log_hard[flow_log_hard$step > 0L &
                                    flow_log_hard$n_excluded > 0L, ]
    n_excl     <- nrow(excl_rows)
    
    # Centre column: enrolled box + one box per non-zero exclusion step
    # Each centre box shows n_remaining AFTER its step's exclusions.
    n_centre   <- n_excl + 1L
    cids       <- c("c0", paste0("c", seq_len(n_excl)))
    
    # n_remaining values for centre boxes:
    # c0 = enrolled total; c1..cn = after each exclusion
    n_vals <- c(enrol_row$n_remaining,
                excl_rows$n_remaining)
    
    # Centre node definitions
    centre_nodes <- purrr::imap_chr(seq_len(n_centre), function(i, ...) {
        nv    <- n_vals[i]
        label <- if (i == 1L)
            glue::glue("Enrolled in OsteoLaus\\nn = {nv}")
        else
            glue::glue("n = {nv}")
        glue::glue(
            '{cids[i]} [label = "{label}", shape = box, ',
            'style = "filled", fillcolor = white, ',
            'color = black, fontname = Helvetica, fontsize = 12]'
        )
    })
    
    # Exclusion box definitions (right column)
    excl_nodes <- purrr::imap_chr(seq_len(n_excl), function(i, ...) {
        row    <- excl_rows[i, ]
        reason <- paste(strwrap(row$reason, width = 35), collapse = "\\n")
        glue::glue(
            'e{i} [label = "Excluded (n = {row$n_excluded})\\n{reason}", ',
            'shape = box, style = "filled", fillcolor = white, ',
            'color = black, fontname = Helvetica, fontsize = 10]'
        )
    })
    
    # Final included box: n_remaining after all exclusion criteria applied.
    # Use min() rather than tail() because zero-excluded steps repeat the same
    # n_remaining value and the last row may not be the most informative.
    final_n <- min(flow_log_hard$n_remaining[flow_log_hard$step > 0L],
                   na.rm = TRUE)
    # If no exclusion steps, final_n equals enrolment total
    if (!is.finite(final_n)) final_n <- enrol_row$n_remaining
    final_node <- glue::glue(
        'cfinal [label = "Included in analysis\\nn = {final_n}", ',
        'shape = box, style = "filled,bold", fillcolor = white, ',
        'color = black, fontname = Helvetica, fontsize = 12]'
    )
    
    # Vertical centre edges: c0->c1->...->cn->cfinal
    centre_edges <- character(0)
    for (i in seq_len(n_excl)) {
        centre_edges <- c(centre_edges,
                          glue::glue("{cids[i]} -> {cids[i + 1L]}")
        )
    }
    last_centre  <- cids[n_centre]
    centre_edges <- c(centre_edges, glue::glue("{last_centre} -> cfinal"))
    
    # Horizontal exclusion edges: ci -> ei (from BEFORE-exclusion node)
    excl_edges <- purrr::imap_chr(seq_len(n_excl), function(i, ...) {
        glue::glue("{cids[i]} -> e{i} [style = dashed, arrowhead = normal]")
    })
    
    # Force horizontal layout for exclusion boxes via rank constraints
    rank_constraints <- purrr::imap_chr(seq_len(n_excl), function(i, ...) {
        glue::glue("{{ rank = same; {cids[i]}; e{i} }}")
    })
    
    dot <- paste(
        "digraph consort {",
        glue::glue('  labelloc = "t"; label = "{title}";'),
        "  rankdir = TB;",
        "  splines = ortho;",
        "  nodesep = 0.4;",
        "  ranksep = 0.5;",
        "  bgcolor = white;",
        "",
        "  // Centre column nodes",
        paste("  ", centre_nodes, collapse = "\n"),
        paste("  ", final_node),
        "",
        "  // Exclusion nodes",
        paste("  ", excl_nodes, collapse = "\n"),
        "",
        "  // Centre edges (vertical)",
        paste("  ", centre_edges, collapse = "\n"),
        "",
        "  // Exclusion edges (horizontal)",
        paste("  ", excl_edges, collapse = "\n"),
        "",
        "  // Rank constraints to force horizontal alignment",
        paste("  ", rank_constraints, collapse = "\n"),
        "}",
        sep = "\n"
    )
    
    DiagrammeR::grViz(dot)
}


# =============================================================================
# Outcome-specific diagram
# =============================================================================

#' Vertical flow diagrams for outcome-specific eligibility, stacked.
#'
#' One vertical CONSORT-style diagram per outcome, displayed sequentially.
#' Each starts from the hard-included count. Only non-zero exclusion steps
#' are shown. Black and white.
#'
#' @param flow_log_outcomes Output of freeze_dataset()$flow_log_outcomes
#'   (named list of per-outcome flow tibbles).
#' @param title             Overall title string.
#' @return DiagrammeR grViz object.
make_outcome_exclusion_graph <- function(
        flow_log_outcomes,
        title = "Outcome-Specific Eligibility") {
    
    .check_diagrammer()
    
    outcome_names <- names(flow_log_outcomes)
    n_outcomes    <- length(outcome_names)
    
    all_nodes <- character(0)
    all_edges <- character(0)
    rank_constraints <- character(0)
    
    # Track the last centre node of each outcome to chain them vertically
    # Each outcome is a self-contained sub-graph with a unique node prefix.
    prev_final <- NULL
    
    for (oi in seq_len(n_outcomes)) {
        nm  <- outcome_names[oi]
        log <- flow_log_outcomes[[nm]]
        
        enrol_row <- log[log$step == 0L, ]
        excl_rows <- log[log$step > 0L & log$n_excluded > 0L, ]
        n_excl    <- nrow(excl_rows)
        px        <- paste0("o", oi, "_")   # node prefix
        
        # Outcome header node
        hdr_label <- paste(
            strwrap(as.character(enrol_row$reason), width = 30),
            collapse = "\\n"
        )
        hdr_id <- paste0(px, "c0")
        all_nodes <- c(all_nodes, glue::glue(
            '{hdr_id} [label = "{hdr_label}\\nn = {enrol_row$n_remaining}", ',
            'shape = box, style = "filled,bold", fillcolor = white, ',
            'color = black, fontname = Helvetica, fontsize = 11]'
        ))
        
        # Link from previous outcome's final node
        if (!is.null(prev_final)) {
            all_edges <- c(all_edges,
                           glue::glue("{prev_final} -> {hdr_id} [style = invis]")
            )
        }
        
        cids  <- c(hdr_id, paste0(px, "c", seq_len(n_excl)))
        n_vals <- c(enrol_row$n_remaining, excl_rows$n_remaining)
        
        # Centre nodes after each exclusion
        for (i in seq_len(n_excl)) {
            cid <- cids[i + 1L]
            all_nodes <- c(all_nodes, glue::glue(
                '{cid} [label = "n = {n_vals[i + 1L]}", ',
                'shape = box, style = "filled", fillcolor = white, ',
                'color = black, fontname = Helvetica, fontsize = 11]'
            ))
            
            # Exclusion box
            eid    <- paste0(px, "e", i)
            reason <- paste(strwrap(excl_rows[i, ]$reason, width = 30),
                            collapse = "\\n")
            all_nodes <- c(all_nodes, glue::glue(
                '{eid} [label = "Excluded (n = {excl_rows[i,]$n_excluded})\\n{reason}", ',
                'shape = box, style = "filled", fillcolor = white, ',
                'color = black, fontname = Helvetica, fontsize = 10]'
            ))
            
            all_edges <- c(all_edges,
                           glue::glue("{cids[i]} -> {cid}"),
                           glue::glue("{cids[i]} -> {eid} [style = dashed, arrowhead = normal]")
            )
            rank_constraints <- c(rank_constraints,
                                  glue::glue("{{ rank = same; {cids[i]}; {eid} }}")
            )
        }
        
        # Final eligible node
        final_n  <- tail(log$n_remaining, 1L)
        final_id <- paste0(px, "final")
        all_nodes <- c(all_nodes, glue::glue(
            '{final_id} [label = "Eligible\\nn = {final_n}", ',
            'shape = box, style = "filled,bold", fillcolor = white, ',
            'color = black, fontname = Helvetica, fontsize = 11]'
        ))
        
        last_cid <- cids[length(cids)]
        all_edges <- c(all_edges, glue::glue("{last_cid} -> {final_id}"))
        prev_final <- final_id
    }
    
    dot <- paste(
        "digraph outcomes {",
        glue::glue('  labelloc = "t"; label = "{title}";'),
        "  rankdir = TB;",
        "  splines = ortho;",
        "  nodesep = 0.4;",
        "  ranksep = 0.5;",
        "  bgcolor = white;",
        "",
        "  // Nodes",
        paste("  ", all_nodes, collapse = "\n"),
        "",
        "  // Edges",
        paste("  ", all_edges, collapse = "\n"),
        "",
        "  // Rank constraints",
        paste("  ", rank_constraints, collapse = "\n"),
        "}",
        sep = "\n"
    )
    
    DiagrammeR::grViz(dot)
}


# =============================================================================
# Convenience wrapper
# =============================================================================

#' Generate both hard and outcome-specific flow diagrams.
#'
#' @param flow_log_hard     Output of freeze_dataset()$flow_log_hard.
#' @param flow_log_outcomes Output of freeze_dataset()$flow_log_outcomes.
#' @return Named list: hard_graph, outcome_graph.
make_combined_flow_graph <- function(flow_log_hard, flow_log_outcomes) {
    list(
        hard_graph    = make_hard_exclusion_graph(flow_log_hard),
        outcome_graph = make_outcome_exclusion_graph(flow_log_outcomes)
    )
}


# =============================================================================
# Export helper
# =============================================================================

#' Export a grViz flow diagram to PNG or SVG.
#'
#' Requires DiagrammeRsvg and rsvg packages.
#'
#' @param graph  DiagrammeR grViz object.
#' @param path   Output file path (.png or .svg).
#' @param width  Width in pixels for PNG output. Default 800.
#' @param height Height in pixels for PNG output. Default 1000.
#' @return Invisibly returns path.
export_exclusion_graph <- function(graph, path,
                                   width  = 800L,
                                   height = 1000L) {
    for (pkg in c("DiagrammeRsvg", "rsvg")) {
        if (!requireNamespace(pkg, quietly = TRUE))
            cli::cli_abort(
                "Package {.pkg {pkg}} required. Install with: \
         install.packages('{pkg}')"
            )
    }
    
    svg_str <- DiagrammeRsvg::export_svg(graph)
    svg_raw <- charToRaw(svg_str)
    
    if (grepl("\\.svg$", path, ignore.case = TRUE)) {
        writeBin(svg_raw, path)
    } else if (grepl("\\.png$", path, ignore.case = TRUE)) {
        rsvg::rsvg_png(svg_raw, path, width = width, height = height)
    } else {
        cli::cli_abort(
            "Unsupported extension in {.path {path}}. Use .svg or .png."
        )
    }
    cli::cli_inform("Flow diagram written to {.path {path}}")
    invisible(path)
}


# =============================================================================
# PRIVATE HELPERS
# =============================================================================

.check_diagrammer <- function() {
    if (!requireNamespace("DiagrammeR", quietly = TRUE))
        cli::cli_abort(
            "Package {.pkg DiagrammeR} required. Install with: \
       install.packages('DiagrammeR')"
        )
}