project:
  type: default

bibliography: sections/references.bib
reference-section-title: References
csl: csl/nlm-citation-sequence-brackets.csl

format:
  pdf:
    documentclass: article
    pdf-engine: lualatex
    number-sections: true
    toc: false
    link-citations: true
    keep-tex: true
    fontsize: 11pt
    linestretch: 1.2
    geometry: margin=2.5cm
    colorlinks: true
    include-in-header:
      text: |
        \usepackage{setspace}
        \usepackage{titlesec}
        \usepackage{titletoc}

        \titleformat{\chapter}[display]
          {\normalfont\huge\bfseries\centering}
          {\chaptertitlename\ \thechapter}{20pt}{\Huge}
        \titlespacing*{\chapter}{0pt}{0pt}{40pt}
          
          % Section formatting
        \titleformat{\section}
          {\normalfont\Large\bfseries\raggedright}
          {\thesection}{1em}{}
        \titlespacing*{\section}{0pt}{3.5ex plus 1ex minus .2ex}{2.3ex plus .2ex}
          
        % Subsection formatting
        \titleformat{\subsection}
          {\normalfont\large\bfseries\raggedright}
          {\thesubsection}{1em}{}
        \titlespacing*{\subsection}{0pt}{3.25ex plus 1ex minus .2ex}{1.5ex plus .2ex}
        
        % Subsubsection formatting
        \titleformat{\subsubsection}
          {\normalfont\normalsize\bfseries\raggedright}
          {\thesubsubsection}{1em}{}
        \titlespacing*{\subsubsection}{0pt}{3.25ex plus 1ex minus .2ex}{1.5ex plus .2ex}
        
        % Paragraph formatting (if needed)
        \titleformat{\paragraph}[runin]
          {\normalfont\normalsize\bfseries}
          {\theparagraph}{1em}{}
        \titlespacing*{\paragraph}{0pt}{3.25ex plus 1ex minus .2ex}{1em}
        
        
        